"""Fuentes de scraping: RSS feeds, web scraping, YouTube channels, GitHub topics."""

FUENTES = {
    "Programa Con Arnau": {"yt":"https://youtube.com/@progconarnau?si=AFBTWjGeo-UpuJdE"},
    "El Pingüino de Mario": {"yt":"https://www.youtube.com/@elpinguinodemario?si=DvMsCTK74FQfFzwH"},
    "MoureDev": {"url": "https://mouredev.com/blog", "yt": "https://www.youtube.com/@mouredev/videos", "selector": "a[href*='/blog/']"},
    "Pelado Nerd": {"yt": "https://www.youtube.com/@PeladoNerd/videos"},
    "Midudev": {"url":"https://midu.dev/", "yt": "https://www.youtube.com/@midudev/videos", "selector": "article a[href]"},
    "Codigo facilito": {"yt": "https://www.youtube.com/@codigofacilito/videos"},
    "Carlos Azaustre": {"url":"https://carlosazaustre.es/blog", "yt": "https://www.youtube.com/@CarlosAzaustre/videos", "selector": "a[href*='/blog/']"},
    "Clipset": {"yt": "https://www.youtube.com/@clipset/videos"},
    "CodelyTV": {"yt": "https://www.youtube.com/@CodelyTV/videos"},
    "EDteam": {"yt": "https://www.youtube.com/@EDteam/videos"},
    "Fazt": {"yt": "https://www.youtube.com/@FaztTech/videos"},
    "FreeCodeCamp": {"yt": "https://www.youtube.com/@freecodecamp/videos"},
    "HolaMundo": {"yt": "https://www.youtube.com/@holamundodev/videos"},
    "Victor Robles": {"yt": "https://www.youtube.com/@victorroblesweb/videos"},
    "Xataka": {"url": "https://www.xataka.com/", "yt":"https://www.youtube.com/@xatakatv/videos", "quick": True, "selector": "article a[href]", "tipo": "noticia"},
    "Genbeta": {"url": "https://www.genbeta.com/", "selector": "article a[href]"},
    "HobbyConsolas": {"url": "https://www.hobbyconsolas.com/tags/temas/tecnologia.html", "selector": "article a[href]"},
    "El País Tecnología": {"url": "https://elpais.com/tecnologia/", "selector": "article a[href]"},
    "Microsiervos": {"url": "https://www.microsiervos.com/", "selector": "article a[href]"},
    "Fundación Carolina": {"url": "https://www.fundacioncarolina.es/", "selector": "h3 a[href]"},
    "Applesfera": {"url": "https://www.applesfera.com/", "selector": "article a[href]"},
    "Wired": {"url": "https://www.wired.com/category/science/"},
    "The Verge": {"url": "https://www.theverge.com/tech"},
    "TechCrunch": {"url": "https://techcrunch.com/category/artificial-intelligence/"},
    "GitHub Blog": {"url": "https://github.blog/category/engineering/", "selector": "article a[href]"},
    "Google AI": {"url": "https://blog.google/technology/ai/", "selector": "article a[href]"},
    "NVIDIA Blog": {"url": "https://blogs.nvidia.com/blog/category/deep-learning/", "selector": "article a[href]"},
    "Ars Technica": {"url": "https://arstechnica.com/gadgets/"},
    "Slashdot": {"url": "https://slashdot.org/", "selector": "article a[href]"},
    "HackTheBox": {"url": "https://www.hackthebox.com/blog/", "selector": "a[href*='/blog/']"},
    # ── Nuevas fuentes ──
    "ADSL Zone": {"url": "https://www.adslzone.net/", "selector": "article h2 a"},
    "MuyComputer": {"url": "https://www.muycomputer.com/", "selector": "a[rel=\"bookmark\"]"},
    "ComputerHoy": {"url": "https://www.computerhoy.com/", "selector": ".c-article__title a"},
    "Hipertextual": {"url": "https://hipertextual.com/"},
    "Hugging Face Blog": {"url": "https://huggingface.co/blog", "selector": "article.overview-card-wrapper a[role=\"link\"]"},
    "Anthropic": {"url": "https://www.anthropic.com/blog", "selector": "a[class*=\"FeaturedGrid\"], a[class*=\"PublicationList\"]"},
    "Meta AI": {"url": "https://engineering.fb.com/category/artificial-intelligence/", "selector": "article a[href]"},
    "DeepMind": {"url": "https://deepmind.google/discover/blog/", "selector": "h3.card__title"},
    "VentureBeat AI": {"url": "https://venturebeat.com/category/ai/", "selector": "header.text-editorial-headline-030 h2 a"},
    "Cactus Compute": {"url": "https://cactuscompute.com/blog", "selector": "article a[href]"},
    # ── Fuentes IA especializadas ──
    "AssemblyAI": {"url": "https://www.assemblyai.com/blog/", "selector": "article h2 a"},
    "Cohere": {"url": "https://cohere.com/blog", "selector": "a[href*='/blog/'] h3"},
    "Scale AI": {"url": "https://scale.com/blog", "selector": "a[href*='/blog/']"},
    "LangChain": {"url": "https://blog.langchain.dev/", "selector": "article h2 a"},
    "Pinecone": {"url": "https://www.pinecone.io/blog/", "selector": "a[href*='/blog/']"},
    "Weights & Biases": {"url": "https://wandb.ai/fully-connected", "selector": "article h2 a"},
    "Hugging Face": {"url": "https://huggingface.co/blog", "selector": "article.overview-card-wrapper a[role='link']"},
    "LlamaIndex": {"url": "https://www.llamaindex.ai/blog", "selector": "a[href*='/blog/']"},
    "Anthropic Research": {"url": "https://www.anthropic.com/research", "selector": "a[class*='card']"},
    "Claude Blog": {"url": "https://docs.anthropic.com/en/release-notes", "selector": "article a[href]"},
    "OpenCode": {"url": "https://opencode.ai/changelog", "selector": "article a[href]"},
    "Google Research": {"url": "https://research.google/blog/", "selector": "a[href*='/blog/']"},
    "Google Cloud AI": {"url": "https://cloud.google.com/blog/products/ai-machine-learning", "selector": "a[href*='/blog/']"},
    "Google AI Dev": {"url": "https://ai.google.dev/", "selector": "article a[href]"},
    "Microsoft AI": {"url": "https://blogs.microsoft.com/ai/", "selector": "article h2 a"},
    "Microsoft Research AI": {"url": "https://www.microsoft.com/en-us/research/topic/artificial-intelligence/", "selector": "article h2 a"},
    "Azure AI": {"url": "https://azure.microsoft.com/en-us/blog/product/azure-ai/", "selector": "article a[href]"},
    "AWS ML": {"url": "https://aws.amazon.com/blogs/machine-learning/", "selector": "article h2 a"},
    "Apple ML Research": {"url": "https://machinelearning.apple.com/", "selector": ".card a[href]"},
    "xAI": {"url": "https://x.ai/blog", "selector": "article h2 a"},
    "Perplexity AI": {"url": "https://blog.perplexity.ai/", "selector": "article h2 a"},
    "Meta AI Research": {"url": "https://ai.meta.com/blog/", "selector": "a[href*='/blog/']"},
    "Stability AI": {"url": "https://stability.ai/news", "selector": "article a[href]"},
    "Replicate": {"url": "https://replicate.com/blog", "selector": "a[href*='/blog/']"},
    "Modal": {"url": "https://modal.com/blog", "selector": "article h2 a"},
    "Together AI": {"url": "https://www.together.ai/blog", "selector": "a[href*='/blog/']"},
    "Fireworks AI": {"url": "https://fireworks.ai/blog", "selector": "a[href*='/blog/']"},
    "Cursor": {"url": "https://www.cursor.com/blog", "selector": "article a[href]"},
    "Codeium": {"url": "https://codeium.com/blog", "selector": "a[href*='/blog/']"},
    "TabbyML": {"url": "https://tabby.tabbyml.com/blog", "selector": "a[href*='/blog/']"},
    "Continue.dev": {"url": "https://docs.continue.dev/changelog", "selector": "article h2 a"},
    "Aider": {"rss": "https://aider.chat/feed.xml", "quick": True},
    # ── GitHub Topics (AI tools, LLMs, agents) ──
    "GitHub Topic AI": {"url": "https://github.com/topics/artificial-intelligence?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic LLM": {"url": "https://github.com/topics/llm?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Agents": {"url": "https://github.com/topics/ai-agents?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic ML": {"url": "https://github.com/topics/machine-learning?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (Video, Content, Git, Docker, Algorithms, OpenSource) ──
    "GitHub Topic Video Editing": {"url": "https://github.com/topics/video-editing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Screen Recording": {"url": "https://github.com/topics/screen-recording?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Content Creation": {"url": "https://github.com/topics/content-creation?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Markdown": {"url": "https://github.com/topics/markdown?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Git": {"url": "https://github.com/topics/git?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Version Control": {"url": "https://github.com/topics/version-control?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Docker": {"url": "https://github.com/topics/docker?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Container": {"url": "https://github.com/topics/container?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Kubernetes": {"url": "https://github.com/topics/kubernetes?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Algorithms": {"url": "https://github.com/topics/algorithms?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Data Structures": {"url": "https://github.com/topics/data-structures?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Competitive Programming": {"url": "https://github.com/topics/competitive-programming?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Generative AI": {"url": "https://github.com/topics/generative-ai?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Coding": {"url": "https://github.com/topics/ai-coding?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Stable Diffusion": {"url": "https://github.com/topics/stable-diffusion?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Video": {"url": "https://github.com/topics/ai-video?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Music": {"url": "https://github.com/topics/ai-music?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Agent": {"url": "https://github.com/topics/ai-agent?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic RAG": {"url": "https://github.com/topics/rag?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Prompt Engineering": {"url": "https://github.com/topics/prompt-engineering?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (AI Tools, Writing, Chatbot, Automation) ──
    "GitHub Topic AI Writing": {"url": "https://github.com/topics/ai-writing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Image Generation": {"url": "https://github.com/topics/ai-image-generation?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Chatbot": {"url": "https://github.com/topics/ai-chatbot?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Automation": {"url": "https://github.com/topics/ai-automation?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Machine Learning": {"url": "https://github.com/topics/machine-learning?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Deep Learning": {"url": "https://github.com/topics/deep-learning?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic NLP": {"url": "https://github.com/topics/nlp?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Tools": {"url": "https://github.com/topics/ai-tools?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Assistant": {"url": "https://github.com/topics/ai-assistant?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Text to Speech": {"url": "https://github.com/topics/text-to-speech?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Speech Recognition": {"url": "https://github.com/topics/speech-recognition?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Audio": {"url": "https://github.com/topics/ai-audio?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Text": {"url": "https://github.com/topics/ai-text?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Open Source AI": {"url": "https://github.com/topics/open-source-ai?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Awesome AI": {"url": "https://github.com/topics/awesome-ai?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Open Source": {"url": "https://github.com/topics/open-source?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Awesome Lists": {"url": "https://github.com/topics/awesome-lists?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (Image, Office, Presentations, Data Workflow) ──
    "GitHub Topic Image Processing": {"url": "https://github.com/topics/image-processing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Image Editing": {"url": "https://github.com/topics/image-editing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Computer Vision": {"url": "https://github.com/topics/computer-vision?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Document Processing": {"url": "https://github.com/topics/document-processing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic PDF": {"url": "https://github.com/topics/pdf?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Office": {"url": "https://github.com/topics/office?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Presentation": {"url": "https://github.com/topics/presentation?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Slide Deck": {"url": "https://github.com/topics/slide-deck?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Data Pipeline": {"url": "https://github.com/topics/data-pipeline?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic ETL": {"url": "https://github.com/topics/etl?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Workflow Automation": {"url": "https://github.com/topics/workflow-automation?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Documentation Generator": {"url": "https://github.com/topics/documentation-generator?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Code Review": {"url": "https://github.com/topics/ai-code-review?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (Meetings, Documentation, AI Agents) ──
    "GitHub Topic Meeting Assistant": {"url": "https://github.com/topics/meeting-assistant?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Transcription": {"url": "https://github.com/topics/transcription?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Speech to Text": {"url": "https://github.com/topics/speech-to-text?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Wiki": {"url": "https://github.com/topics/wiki?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Knowledge Base": {"url": "https://github.com/topics/knowledge-base?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── Repos específicos innovadores ──
    "OpenWiki": {"url": "https://github.com/langchain-ai/openwiki", "tipo": "herramienta", "subtipo": "github-repo", "selector": "article a[href]"},
    "Meetily": {"url": "https://github.com/Zackriya-Solutions/meetily", "tipo": "herramienta", "subtipo": "github-repo", "selector": "article a[href]"},
    "Code-to-Docs": {"url": "https://github.com/redhat-community-ai-tools/code-to-docs", "tipo": "herramienta", "subtipo": "github-repo", "selector": "article a[href]"},
    "AutoPR": {"url": "https://github.com/irgolic/autopr", "tipo": "herramienta", "subtipo": "github-repo", "selector": "article a[href]"},
    "PR-Agent": {"url": "https://github.com/qodo-ai/pr-agent", "tipo": "herramienta", "subtipo": "github-repo", "selector": "article a[href]"},
    # ── GitHub Topics (Web Standards, Linux Config, Best Practices) ──
    "GitHub Topic CSS": {"url": "https://github.com/topics/css?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic HTML": {"url": "https://github.com/topics/html?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Web Standards": {"url": "https://github.com/topics/web-standards?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Frontend": {"url": "https://github.com/topics/frontend?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Linux Config": {"url": "https://github.com/topics/linux-config?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Dotfiles": {"url": "https://github.com/topics/dotfiles?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Linux Admin": {"url": "https://github.com/topics/linux-admin?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Best Practices": {"url": "https://github.com/topics/best-practices?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Coding Guidelines": {"url": "https://github.com/topics/coding-guidelines?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Style Guide": {"url": "https://github.com/topics/style-guide?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (Design Tools, UI/UX, Vector) ──
    "GitHub Topic UI/UX": {"url": "https://github.com/topics/ui-ux?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Design Tools": {"url": "https://github.com/topics/design-tools?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Vector Graphics": {"url": "https://github.com/topics/vector-graphics?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic AI Design": {"url": "https://github.com/topics/ai-design?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Figma": {"url": "https://github.com/topics/figma?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Design System": {"url": "https://github.com/topics/design-system?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Component Library": {"url": "https://github.com/topics/component-library?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic UI Components": {"url": "https://github.com/topics/ui-components?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── GitHub Topics (XML, YAML, web dev) ──
    "GitHub Topic XML": {"url": "https://github.com/topics/xml?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic YAML": {"url": "https://github.com/topics/yaml?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── RSS/Web: Web Standards (CSS, HTML, XML, YAML, web dev) ──
    "web.dev": {"rss": "https://web.dev/feed.xml", "quick": True},
    "MDN Blog": {"rss": "https://developer.mozilla.org/en-US/blog/rss.xml", "quick": True},
    "CSS-Tricks": {"rss": "https://css-tricks.com/feed/", "quick": True},
    "Smashing Magazine": {"rss": "https://www.smashingmagazine.com/feed/", "quick": True},
    "Can I Use": {"rss": "https://caniuse.com/feed", "quick": True},
    "Chrome Developers": {"rss": "https://developer.chrome.com/blog/feed.xml", "quick": True},
    "W3C Blog": {"rss": "https://www.w3.org/blog/feed/", "quick": True},
    # ── RSS/Web: Linux, DevOps, Infraestructura ──
    "Linux.com": {"rss": "https://www.linux.com/feed/", "quick": True},
    "Hacker News": {"rss": "https://hnrss.org/frontpage", "quick": True},
    "Lobsters": {"rss": "https://lobste.rs/rss", "quick": True},
    "InfoQ": {"rss": "https://www.infoq.com/feed/", "quick": True},
    # ── RSS/Web: General Tech, AI, Science ──
    "Ars Technica": {"rss": "https://feeds.arstechnica.com/arstechnica/index", "quick": True},
    "OpenAI Blog": {"rss": "https://openai.com/news/rss.xml", "quick": True},
    "Google AI Blog": {"rss": "https://blog.google/technology/ai/rss/", "quick": True},
    # ── Trending GitHub diario ──
    "GitHub Trending Daily": {"url": "https://github.com/trending?since=daily", "tipo": "herramienta", "subtipo": "github", "selector": "article a[href]"},
    "GitHub Trending Weekly": {"url": "https://github.com/trending?since=weekly", "tipo": "herramienta", "subtipo": "github", "selector": "article a[href]"},
    # ── Noticias generales IA ──
    "BBC AI": {"url": "https://www.bbc.com/news/topics/c302m85qtk1t", "selector": "a[data-testid='internal-link']"},
    "El Mundo Tecnología": {"url": "https://www.elmundo.es/tecnologia.html", "selector": "article a[href]"},
    # ── Más creadores de contenido (YouTube + redes) ──
    "LinkTV": {"yt": "https://www.youtube.com/@LinkTVA/videos"},
    "Ringa Tech": {"yt": "https://www.youtube.com/@RingaTech/videos"},
    "Nethermind": {"yt": "https://www.youtube.com/@NethermindDev/videos"},
    "Develoteca": {"yt": "https://www.youtube.com/@Develoteca/videos"},
    "Linkfydev": {"yt": "https://www.youtube.com/@Linkfydev/videos"},
    "Esa Operativa": {"yt": "https://www.youtube.com/@EsaOperativa/videos"},
    "Programador X": {"yt": "https://www.youtube.com/@ProgramadorX/videos"},
    # ── Subscripciones de @jorbencas ──
    "3DHumbe": {"yt": "https://www.youtube.com/@3DHumbe/videos"},
    "4tomik": {"yt": "https://www.youtube.com/@4tomik434/videos"},
    "AfroCode": {"yt": "https://www.youtube.com/@Afro-code/videos"},
    "Agustín Medina | AI Agency Academy": {"yt": "https://www.youtube.com/@agustinmedinaIA/videos"},
    "Aivars Meijers": {"yt": "https://www.youtube.com/@AivarsMeijers/videos"},
    "ALDI SCRAP PCB": {"yt": "https://www.youtube.com/@aldiscrap/videos"},
    "aleccisWithX": {"yt": "https://www.youtube.com/@alecciswithx9137/videos"},
    "Alejandro Pérez": {"yt": "https://www.youtube.com/@alejandroperez/videos"},
    "AlexCG Design": {"yt": "https://www.youtube.com/@AlexCGDesign/videos"},
    "Antonio Sarosi": {"yt": "https://www.youtube.com/@AntonioSarosi/videos"},
    "AprenDevOps": {"yt": "https://www.youtube.com/@AprenDevOps/videos"},
    "Aprendiendo Frontend": {"yt": "https://www.youtube.com/@AprendiendoFrontendChannel/videos"},
    "Atípico Mental": {"yt": "https://www.youtube.com/@atipicomental/videos"},
    "BettaTech": {"yt": "https://www.youtube.com/@BettaTech/videos"},
    "Bita Byte Ibiza": {"yt": "https://www.youtube.com/@bitabyteibiza1177/videos"},
    "Bro Code": {"yt": "https://www.youtube.com/@BroCodez/videos"},
    "campusMVP.es": {"yt": "https://www.youtube.com/@campusmvp/videos"},
    "Carlos Alfaro": {"yt": "https://www.youtube.com/@CarlosAlfaroSV/videos"},
    "Carlos Azaustre Two": {"yt": "https://www.youtube.com/@CarlosAzaustreTV/videos"},
    "Chilango Radio": {"yt": "https://www.youtube.com/@chilangoradiomx/videos"},
    "Clever Programmer": {"yt": "https://www.youtube.com/@CleverProgrammer/videos"},
    "clipset shorts": {"yt": "https://www.youtube.com/@clipsetshorts/videos"},
    "ClipsetTEST": {"yt": "https://www.youtube.com/@testunit/videos"},
    "Code Monkey": {"yt": "https://www.youtube.com/@CodeMonkeyUnity/videos"},
    "CodeBorn Dev": {"yt": "https://www.youtube.com/@codeborn-dev/videos"},
    "Codificandolo": {"yt": "https://www.youtube.com/@codificandolo/videos"},
    "Codigo Estudiante": {"yt": "https://www.youtube.com/@codigoestudiante/videos"},
    "Consejos C#": {"yt": "https://www.youtube.com/@ConsejosCSharp/videos"},
    "Contando Bits": {"yt": "https://www.youtube.com/@ContandoBits/videos"},
    "Control 3D": {"yt": "https://www.youtube.com/@Control3D/videos"},
    "Cristian Torres": {"yt": "https://www.youtube.com/@krizalfaro/videos"},
    "d3vcloud": {"yt": "https://www.youtube.com/@d3vcloud/videos"},
    "Daniel Diaz": {"yt": "https://www.youtube.com/@DanielDiazGranizo/videos"},
    "DanieloTech": {"yt": "https://www.youtube.com/@danielotech/videos"},
    "DesarrolloWeb.com": {"yt": "https://www.youtube.com/@deswebcom/videos"},
    "DesignCourse": {"yt": "https://www.youtube.com/@DesignCourse/videos"},
    "Devon Crawford": {"yt": "https://www.youtube.com/@DevonCrawford/videos"},
    "diegoveloper": {"yt": "https://www.youtube.com/@diegoveloper/videos"},
    "DistroTube": {"yt": "https://www.youtube.com/@DistroTube/videos"},
    "Domingo Gomes": {"yt": "https://www.youtube.com/@new3sc/videos"},
    "dotnet": {"yt": "https://www.youtube.com/@dotnet/videos"},
    "Enrique Dans": {"yt": "https://www.youtube.com/@edans/videos"},
    "FalconMasters": {"yt": "https://www.youtube.com/@FalconMasters/videos"},
    "Fazt Code": {"yt": "https://www.youtube.com/@FaztCode/videos"},
    "Fernando Herrera": {"yt": "https://www.youtube.com/@fernando_her85/videos"},
    "freeCodeCamp Español": {"yt": "https://www.youtube.com/@freecodecampes/videos"},
    "GitHub": {"yt": "https://www.youtube.com/@GitHub/videos"},
    "Google": {"yt": "https://www.youtube.com/@Google/videos"},
    "GoogleDoodles": {"yt": "https://www.youtube.com/@googledoodles/videos"},
    "grenasfrijolito": {"yt": "https://www.youtube.com/@grenasfrijolito/videos"},
    "Guillermo Garcia": {"yt": "https://www.youtube.com/@GuillermoGarcia46840/videos"},
    "Hallden": {"yt": "https://www.youtube.com/@Hallden_/videos"},
    "Hdeleon Clips": {"yt": "https://www.youtube.com/@hdeleonClips/videos"},
    "hdeleon.net": {"yt": "https://www.youtube.com/@hdeleonnet/videos"},
    "IA con Daniel": {"yt": "https://www.youtube.com/@IAconDaniel/videos"},
    "IAmTimCorey": {"yt": "https://www.youtube.com/@IAmTimCorey/videos"},
    "Ildefonso Segura Tutoriales": {"yt": "https://www.youtube.com/@ildefonsosegura/videos"},
    "IndevError": {"yt": "https://www.youtube.com/@IndevError/videos"},
    "Informatic.com": {"yt": "https://www.youtube.com/@ProgramaInformatic/videos"},
    "Informática DP": {"yt": "https://www.youtube.com/@informaticadp/videos"},
    "Internet no pesa nada": {"yt": "https://www.youtube.com/@internetnopesanada/videos"},
    "JD Productions HD": {"yt": "https://www.youtube.com/@MrJDTutoriales/videos"},
    "Jerry Sawhney": {"yt": "https://www.youtube.com/@Innovativecoder/videos"},
    "Jesse Dietrichson": {"yt": "https://www.youtube.com/@JesseDietrichson/videos"},
    "Jesus Luque Medina": {"yt": "https://www.youtube.com/@JesusLuqueMedina/videos"},
    "Jorebza": {"yt": "https://www.youtube.com/@Jorebza/videos"},
    "Jose Maria Alonso": {"yt": "https://www.youtube.com/@MalignoAlonso/videos"},
    "jotajotavm": {"yt": "https://www.youtube.com/@jotajotavm/videos"},
    "JustDjango": {"yt": "https://www.youtube.com/@justdjango/videos"},
    "Kala360Gamer": {"yt": "https://www.youtube.com/@Kala360Gamer/videos"},
    "Karan Kumar": {"yt": "https://www.youtube.com/@krn-751/videos"},
    "Kiko Palomares": {"yt": "https://www.youtube.com/@kikopalomares/videos"},
    "Leigh en Español": {"yt": "https://www.youtube.com/@LeighenEspañol/videos"},
    "Leonidas Esteban": {"yt": "https://www.youtube.com/@LeonidasEsteban/videos"},
    "LinuxScoop": {"yt": "https://www.youtube.com/@linuxscoop/videos"},
    "linuxware": {"yt": "https://www.youtube.com/@iqpi18/videos"},
    "Luis Cambra": {"yt": "https://www.youtube.com/@LuisCambraps/videos"},
    "Make it Real": {"yt": "https://www.youtube.com/@MakeitrealCamp1/videos"},
    "makigas": {"yt": "https://www.youtube.com/@makigas/videos"},
    "ManzDev": {"yt": "https://www.youtube.com/@ManzDev/videos"},
    "Martín Gesualdo": {"yt": "https://www.youtube.com/@migesualdo/videos"},
    "Microsoft Developer": {"yt": "https://www.youtube.com/@MicrosoftDeveloper/videos"},
    "Microsoft IoT Developers": {"yt": "https://www.youtube.com/@MicrosoftIoTDevelopers/videos"},
    "midulive": {"yt": "https://www.youtube.com/@midulive/videos"},
    "Migma": {"yt": "https://www.youtube.com/@xMigma/videos"},
    "Moldeo Interactive": {"yt": "https://www.youtube.com/@moldeointeractive/videos"},
    "MoureDev TV": {"yt": "https://www.youtube.com/@mouredevtv/videos"},
    "Mr. Resumen": {"yt": "https://www.youtube.com/@MrResumen/videos"},
    "Mundos Apple Pro": {"yt": "https://www.youtube.com/@MundosApplePro/videos"},
    "Món de llengua - Dr. Zalbidea": {"yt": "https://www.youtube.com/@Móndellengua-Dr.Zalbidea/videos"},
    "NASeros": {"yt": "https://www.youtube.com/@naseros/videos"},
    "Nekszer": {"yt": "https://www.youtube.com/@NEKSZER/videos"},
    "nicobytes": {"yt": "https://www.youtube.com/@nicobytes/videos"},
    "No es Brujería, es Tecnología": {"yt": "https://www.youtube.com/@brujeriatech/videos"},
    "Noticias Tech y ya!": {"yt": "https://www.youtube.com/@NoticiasTechyya/videos"},
    "Octarine Code": {"yt": "https://www.youtube.com/@OctarineCode/videos"},
    "Online Tutorials": {"yt": "https://www.youtube.com/@OnlineTutorialsYT/videos"},
    "PhoneGapSpain": {"yt": "https://www.youtube.com/@PhoneGapSpain/videos"},
    "Pildoras de programación": {"yt": "https://www.youtube.com/@pildorasdeprogramacion/videos"},
    "pildorasinformaticas": {"yt": "https://www.youtube.com/@pildorasinformaticas/videos"},
    "Pirple": {"yt": "https://www.youtube.com/@Pirple/videos"},
    "Platzi": {"yt": "https://www.youtube.com/@Platzi/videos"},
    "Programación en español": {"yt": "https://www.youtube.com/@programacion-es/videos"},
    "Programming w/ Professor Sluiter": {"yt": "https://www.youtube.com/@shadsluiter/videos"},
    "Programming with Mosh": {"yt": "https://www.youtube.com/@programmingwithmosh/videos"},
    "React-Native by Wilhelm": {"yt": "https://www.youtube.com/@reactuikit/videos"},
    "Ready Set Click": {"yt": "https://www.youtube.com/@readysetclick9870/videos"},
    "render2web": {"yt": "https://www.youtube.com/@render2web/videos"},
    "RobotSolar": {"yt": "https://www.youtube.com/@robotsolar7783/videos"},
    "Sergio Alejandro Campos - EXCELeINFO": {"yt": "https://www.youtube.com/@SergioAlejandroCampos/videos"},
    "Simon Grimm": {"yt": "https://www.youtube.com/@galaxies_dev/videos"},
    "Sin Rueda Tecnológica": {"yt": "https://www.youtube.com/@sinruedatecnologica/videos"},
    "Software Lion": {"yt": "https://www.youtube.com/@softwarelion-oficial/videos"},
    "Sonfil": {"yt": "https://www.youtube.com/@Sonfil/videos"},
    "Sonny Sangha": {"yt": "https://www.youtube.com/@SonnySangha/videos"},
    "Sosteniblevida": {"yt": "https://www.youtube.com/@Sosteniblevida/videos"},
    "Soy Dalto": {"yt": "https://www.youtube.com/@soydalto/videos"},
    "subelealruido": {"yt": "https://www.youtube.com/@subelealruido/videos"},
    "Super Excel": {"yt": "https://www.youtube.com/@super-excel/videos"},
    "Tech Point Fundamentals": {"yt": "https://www.youtube.com/@TechPointFundamentals/videos"},
    "TechHut": {"yt": "https://www.youtube.com/@TechHut/videos"},
    "TecnoBinaria": {"yt": "https://www.youtube.com/@Tecnobinaria/videos"},
    "TecnoXplora": {"yt": "https://www.youtube.com/@TecnoXplora/videos"},
    "TEDx Talks": {"yt": "https://www.youtube.com/@TEDx/videos"},
    "The Coder Cave | Programación y Tecnología": {"yt": "https://www.youtube.com/@TheCoderCave/videos"},
    "TIFF Trailers": {"yt": "https://www.youtube.com/@TIFFTrailers/videos"},
    "Toni Dev": {"yt": "https://www.youtube.com/@tonidev_/videos"},
    "Topes de Gama": {"yt": "https://www.youtube.com/@TopesdeGama/videos"},
    "Tu Area De Informatica": {"yt": "https://www.youtube.com/@TuAreaDeInformatica/videos"},
    "tutorialesJJ": {"yt": "https://www.youtube.com/@tutorialesJJ/videos"},
    "tutorialsEU": {"yt": "https://www.youtube.com/@tutorialsEU/videos"},
    "Unity": {"yt": "https://www.youtube.com/@unity/videos"},
    "Victor Abarca": {"yt": "https://www.youtube.com/@VictorAbarca/videos"},
    "Vida MRR - Programacion web": {"yt": "https://www.youtube.com/@vidamrr/videos"},
    "Video Tutoriales Android": {"yt": "https://www.youtube.com/@VideoTutorialesAndroidMovil/videos"},
    "Web Dev Simplified": {"yt": "https://www.youtube.com/@WebDevSimplified/videos"},
    # ── Tech news ──
    "ZDNet": {"url": "https://www.zdnet.com/topic/artificial-intelligence/", "selector": "article h3 a"},
    "CNET": {"url": "https://www.cnet.com/tech/", "selector": "a[class*='title']"},
    "Android Authority": {"url": "https://www.androidauthority.com/", "selector": "h3 a"},
    "The Next Web": {"url": "https://thenextweb.com/topic/artificial-intelligence", "selector": "article h2 a"},
    "InfoWorld": {"url": "https://www.infoworld.com/category/artificial-intelligence/", "selector": "article a[href]"},
    # ── Blogs de desarrollo ──
    "LogRocket": {"url": "https://blog.logrocket.com/", "selector": "a[class*='card']"},
    "Smashing Magazine": {"url": "https://www.smashingmagazine.com/articles/", "selector": "article h2 a"},
    "CSS-Tricks": {"url": "https://css-tricks.com/", "selector": "article h2 a"},
    "freeCodeCamp": {"url": "https://www.freecodecamp.org/news/", "selector": "article h2 a"},
    "DigitalOcean": {"url": "https://www.digitalocean.com/blog", "selector": "a[class*='blog-card'] h3"},
    # ── Fuentes de modelos de IA ──
    "MiniMax": {"url": "https://minimax.io/blog", "selector": "a[href*='/blog/']"},
    "DeepSeek": {"url": "https://deepseek.com/blog", "selector": "article h2 a"},
    "Qwen": {"url": "https://qwen.readthedocs.io/en/latest/", "selector": "article h2 a"},
    "AI21 Labs": {"url": "https://www.ai21.com/blog", "selector": "article h2 a"},
    # ── Más fuentes IA y tecnología ──
    "The Decoder": {"url": "https://the-decoder.com/", "selector": "article a[href]"},
    "MarkTechPost": {"url": "https://www.marktechpost.com/", "selector": "h3 a[href]"},
    "LinkedIn Engineering": {"url": "https://engineering.linkedin.com/blog", "selector": ".post-title a"},
    "Facebook Engineering": {"url": "https://engineering.fb.com/", "selector": "article a[href]"},
    # ── Noticias IA: herramientas, modelos, comparativas ──
    "AI Bytes": {"url": "https://aibytes.blog/", "selector": "article a[href]", "quick": True, "tipo": "noticia"},
    "ToolChase": {"url": "https://toolchase.com/blog/", "selector": "a[href*='/blog/']", "quick": True, "tipo": "noticia"},
    "ThePlanetTools": {"url": "https://theplanettools.ai/", "selector": "a[class*='card']", "quick": True, "tipo": "noticia"},
    "CompareThe.ai": {"url": "https://www.comparethe.ai/blog", "selector": "a[href*='/blog/']", "quick": True, "tipo": "noticia"},
    "YourAIChoice": {"url": "https://youraichoice.com/", "selector": "article h2 a, h3 a", "quick": True, "tipo": "noticia"},
    "DeeperInsights": {"url": "https://deeperinsights.com/ai-review/", "selector": "a[class*='card']", "quick": True, "tipo": "noticia"},
    "AI Weekly": {"url": "https://aiweekly.co/", "selector": "h2 a", "quick": True, "tipo": "noticia"},
    "NeelsWorld": {"url": "https://neelsworld.in/", "selector": "article h2 a, h3 a", "quick": True, "tipo": "noticia"},
    "CleverAI": {"url": "https://cleverai.app/es/blog", "selector": "article a[href]", "quick": True, "tipo": "noticia"},
    "IA News": {"url": "https://ia-news.es/", "selector": ".card a[href]", "quick": True, "tipo": "noticia"},
    "DonWeb IA": {"url": "https://blog.donweb.com/ia-todos-lados-2026/", "selector": "article a[href]", "quick": True, "tipo": "noticia"},

    # ── Fuentes RSS (lectores XML) [quick: True → tier light] ──
    "GitHub Engineering": {"rss": "https://github.blog/engineering/feed/", "quick": True},
    "Stack Overflow Blog": {"rss": "https://stackoverflow.blog/feed/", "quick": True},
    "Hacker News": {"rss": "https://hnrss.org/frontpage", "quick": True},
    "Google AI Blog": {"rss": "https://blog.google/technology/ai/rss/", "quick": True},
    "MIT Tech Review AI": {"rss": "https://www.technologyreview.com/topic/artificial-intelligence/feed/", "quick": True},
    "Google Search Central": {"rss": "https://developers.google.com/search/blog/feed.xml", "quick": True},
    "Moz Blog SEO": {"rss": "https://moz.com/blog/feed.xml", "quick": True},
    "Search Engine Journal": {"rss": "https://www.searchenginejournal.com/feed/", "quick": True},
    "Wired AI": {"rss": "https://www.wired.com/feed/rss", "quick": True},
    "TechCrunch AI": {"rss": "https://techcrunch.com/category/artificial-intelligence/feed/", "quick": True},
    "Ars Technica AI": {"rss": "https://feeds.arstechnica.com/arstechnica/index", "quick": True},
    "Dev.to": {"rss": "https://dev.to/feed", "quick": True},
    # ── IA empresas: web scraping (sin RSS) ──
    "Anthropic Research": {"url": "https://www.anthropic.com/research", "selector": "a[href*='/research/']", "tipo": "noticia", "quick": True},
    "Ollama Blog": {"url": "https://ollama.com/blog", "selector": "a[href^='/blog/'] h2", "tipo": "noticia", "quick": True},
    "Mistral News": {"url": "https://mistral.ai/news", "selector": "a[href^='/news/']", "tipo": "noticia", "quick": True},
    "Cohere Blog": {"url": "https://cohere.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "LangChain Blog": {"url": "https://blog.langchain.dev", "selector": "a[href*='/p/'] h2, a[href*='/p/'] h3", "tipo": "noticia", "quick": True},
    "Google Developers Blog": {"url": "https://developers.googleblog.com/en/", "selector": ".post-item__link, a.glue-carousel__item", "tipo": "noticia", "quick": True},
    "HuggingFace Papers": {"url": "https://huggingface.co/papers", "selector": "article a", "tipo": "noticia", "quick": True},
    "Mozilla Hacks": {"url": "https://hacks.mozilla.org", "selector": "h3.post__title a", "tipo": "noticia", "quick": True},
    # ── IA China: RSS + web scraping ──
    "量子位 (QbitAI)": {"rss": "https://www.qbitai.com/feed", "quick": True},
    "36氪 AI": {"rss": "https://36kr.com/feed", "quick": True},
    "Qwen Blog": {"url": "https://qwen.ai/blog", "selector": "article h2, .post h2", "tipo": "noticia", "quick": True},
    "DeepSeek Blog": {"url": "https://api-docs.deepseek.com/", "selector": "article a[href]", "tipo": "noticia", "quick": True},
    "01.AI News": {"url": "https://01.ai/", "selector": ".news-item a, a[href*='news']", "tipo": "noticia", "quick": True},
    "THUDM ChatGLM": {"rss": "https://github.com/zai-org/ChatGLM3/releases.atom", "quick": True},
    # ── Noticias tech y general ──
    "Business Insider Big Tech": {"rss": "https://www.businessinsider.es/rss/big-tech/", "url": "https://www.businessinsider.es/big-tech/", "selector": "article h2 a", "quick": True, "tipo": "noticia"},
    "Business Insider Tecnología": {"rss": "https://www.businessinsider.es/rss/tecnologia/", "url": "https://www.businessinsider.es/tecnologia/", "selector": "article h2 a", "quick": True, "tipo": "noticia"},
    "Hipertextual": {"rss": "https://hipertextual.com/feed/", "quick": True},
    "ADSL Zone": {"rss": "https://www.adslzone.net/feed", "quick": True},
    "MuyComputer": {"rss": "https://www.muycomputer.com/feed/", "quick": True},
    "The Verge": {"rss": "https://www.theverge.com/rss/index.xml", "quick": True},
    "TechCrunch": {"rss": "https://techcrunch.com/feed/", "quick": True},
    "Wired": {"rss": "https://www.wired.com/feed/rss", "quick": True},
    "Ars Technica": {"rss": "https://feeds.arstechnica.com/arstechnica/index", "quick": True},
    "Engadget": {"rss": "https://www.engadget.com/rss.xml", "quick": True},
    "ZDNet": {"rss": "https://www.zdnet.com/news/rss.xml", "quick": True},
    "CNET": {"rss": "https://www.cnet.com/rss/news/", "quick": True},
    "Tom's Hardware": {"rss": "https://www.tomshardware.com/feeds/all", "quick": True},
    # ── Google, Apple, Microsoft ──
    "Google Blog": {"rss": "https://blog.google/rss/", "quick": True},
    "Apple Newsroom": {"rss": "https://www.apple.com/newsroom/rss-feed.rss", "quick": True},
    "Microsoft Dev Blog": {"rss": "https://devblogs.microsoft.com/feed/", "quick": True},
    # ── Astro framework ──
    "Astro Blog": {"url": "https://astro.build/blog/", "selector": "a[href^='/blog/']", "tipo": "noticia", "quick": True},
    "Astro GitHub Releases": {"rss": "https://github.com/withastro/astro/releases.atom", "quick": True},
    # ── Software libre y Open Source ──
    "Phoronix": {"rss": "https://www.phoronix.com/rss.php", "quick": True},
    "OMG Ubuntu": {"rss": "https://www.omgubuntu.co.uk/feed", "quick": True},
    "It's FOSS": {"rss": "https://itsfoss.com/feed/", "quick": True},
    "Docker Blog": {"rss": "https://www.docker.com/blog/feed/", "quick": True},
    "Kubernetes Blog": {"rss": "https://kubernetes.io/feed.xml", "quick": True},
    # ── Sandbox, herramientas IA, infraestructura ──
    "Vercel Blog": {"rss": "https://vercel.com/atom", "quick": True},
    "Cloudflare Blog": {"rss": "https://blog.cloudflare.com/rss/", "quick": True},
    "Railway Blog": {"rss": "https://blog.railway.app/rss.xml", "quick": True},
    # ── AI Research / Papers ──
    "AI Alignment Forum": {"rss": "https://www.alignmentforum.org/feed.xml", "quick": True},
    "LessWrong AI": {"rss": "https://www.lesswrong.com/feed.xml", "quick": True},
    "Machine Learning Mastery": {"rss": "https://machinelearningmastery.com/feed/", "quick": True},
    "NVIDIA Developer Blog": {"rss": "https://developer.nvidia.com/blog/feed/", "quick": True},
    # ── Seguridad y DevOps ──
    "Krebs on Security": {"rss": "https://krebsonsecurity.com/feed/", "quick": True},
    "The Hacker News": {"rss": "https://feeds.feedburner.com/TheHackersNews", "quick": True},
    "SANS ISC": {"rss": "https://isc.sans.edu/rssfeed.xml", "quick": True},
    "HashiCorp Blog": {"rss": "https://www.hashicorp.com/blog/feed.xml", "quick": True},
    # ── Ciberseguridad y Vulnerabilidades ──
    "BleepingComputer": {"rss": "https://www.bleepingcomputer.com/feed/", "quick": True},
    "SecurityWeek": {"rss": "https://feeds.feedburner.com/securityweek", "quick": True},
    "Dark Reading": {"rss": "https://www.darkreading.com/rss.xml", "quick": True},
    "Schneier on Security": {"rss": "https://www.schneier.com/feed/atom/", "quick": True},
    "The Record": {"rss": "https://therecord.media/feed/", "quick": True},
    "CyberScoop": {"rss": "https://cyberscoop.com/feed/", "quick": True},
    "SC Media": {"rss": "https://www.scworld.com/feed", "quick": True},
    "Help Net Security": {"rss": "https://www.helpnetsecurity.com/feed/", "quick": True},
    "PortSwigger Research": {"rss": "https://portswigger.net/research/rss", "quick": True},
    "NVD - National Vulnerability Database": {"url": "https://nvd.nist.gov/vuln/search", "selector": "a[href*='/vuln/detail/']", "tipo": "noticia", "quick": True},
    "CVE Details": {"url": "https://www.cvedetails.com/vulnerability-feed.php", "selector": "a[href*='/vulnerability/']", "tipo": "noticia", "quick": True},
    "GitHub Advisory Database": {"rss": "https://github.com/advisories.atom", "quick": True},
    "Snyk Blog": {"rss": "https://snyk.io/blog/feed/", "quick": True},
    "Sonatype Blog": {"rss": "https://blog.sonatype.com/rss.xml", "quick": True},
    "OWASP Blog": {"rss": "https://owasp.org/feed.xml", "quick": True},
    "Trellix Research": {"rss": "https://www.trellix.com/blogs/research/rss/", "quick": True},
    "SentinelOne Labs": {"rss": "https://www.sentinelone.com/blog/feed/", "quick": True},
    "Elastic Security Labs": {"rss": "https://www.elastic.co/security-labs/rss/feed.xml", "quick": True},
    "Cisco Security Blog": {"rss": "https://blogs.cisco.com/security/feed", "quick": True},
    "Palo Alto Networks Blog": {"rss": "https://www.paloaltonetworks.com/blog/feed/", "quick": True},
    "CrowdStrike Blog": {"rss": "https://www.crowdstrike.com/blog/feed/", "quick": True},
    "Mandiant Blog": {"rss": "https://www.mandiant.com/resources/blog/rss.xml", "quick": True},
    "Unit 42 (Palo Alto)": {"rss": "https://unit42.paloaltonetworks.com/feed/", "quick": True},
    "Rapid7 Blog": {"rss": "https://www.rapid7.com/blog/feed/", "quick": True},
    "Qualys Blog": {"rss": "https://blog.qualys.com/feed", "quick": True},
    "Tenable Blog": {"rss": "https://www.tenable.com/blog/feed", "quick": True},
    "ZDI Blog": {"rss": "https://www.zerodayinitiative.com/blog/feed", "quick": True},
    "Packet Storm": {"rss": "https://rss.packetstormsecurity.com/", "quick": True},
    "Exploit Database": {"rss": "https://www.exploit-db.com/rss.xml", "quick": True},
    "Full Disclosure": {"rss": "https://seclists.org/rss/fulldisclosure.rss", "quick": True},
    "Bugtraq": {"rss": "https://seclists.org/rss/bugtraq.rss", "quick": True},
    "Google Project Zero": {"rss": "https://googleprojectzero.blogspot.com/feeds/posts/default", "quick": True},
    "Microsoft Security Blog": {"rss": "https://www.microsoft.com/en-us/security/blog/feed/", "quick": True},
    "Apple Security": {"rss": "https://support.apple.com/en-us/HT201222", "quick": True},
    "Mozilla Security Blog": {"rss": "https://blog.mozilla.org/security/feed/", "quick": True},
    "Cloudflare Blog": {"rss": "https://blog.cloudflare.com/rss/", "quick": True},
    "AWS Security Blog": {"rss": "https://aws.amazon.com/blogs/security/feed/", "quick": True},
    "Google Security Blog": {"rss": "https://security.googleblog.com/feeds/posts/default", "quick": True},
    "Wordfence Blog": {"rss": "https://www.wordfence.com/blog/feed/", "quick": True},
    "Sucuri Blog": {"rss": "https://blog.sucuri.net/feed", "quick": True},
    "Detectify Blog": {"rss": "https://blog.detectify.com/feed/", "quick": True},
    "Imperva Blog": {"rss": "https://www.imperva.com/blog/feed/", "quick": True},
    "Arctic Wolf Blog": {"rss": "https://arcticwolf.com/blog/feed/", "quick": True},
    "Varonis Blog": {"rss": "https://www.varonis.com/blog/feed/", "quick": True},
    "Proofpoint Blog": {"rss": "https://www.proofpoint.com/us/blog/rss.xml", "quick": True},
    "Fortinet Blog": {"rss": "https://www.fortinet.com/blog/threat-research/rss.xml", "quick": True},
    "Check Point Research": {"rss": "https://research.checkpoint.com/feed/", "quick": True},
    "Kaspersky Securelist": {"rss": "https://securelist.com/feed/", "quick": True},
    "Avast Decoded": {"rss": "https://decoded.avast.io/feed/", "quick": True},
    "Bitdefender Labs": {"rss": "https://www.bitdefender.com/blog/labs/feed/", "quick": True},
    "Malwarebytes Labs": {"rss": "https://www.malwarebytes.com/blog/feed", "quick": True},
    "Sophos News": {"rss": "https://nakedsecurity.sophos.com/feed/", "quick": True},
    "Trend Micro Research": {"rss": "https://www.trendmicro.com/en_us/research.html/rss", "quick": True},
    "Zscaler ThreatLabz": {"rss": "https://www.zscaler.com/blogs/security-research/feed", "quick": True},
    "Recorded Future": {"rss": "https://www.recordedfuture.com/feed", "quick": True},
    "Volexity Blog": {"rss": "https://www.volexity.com/blog/feed/", "quick": True},
    "Mandiant": {"rss": "https://www.mandiant.com/resources/blog/rss.xml", "quick": True},
    "Huntress Blog": {"rss": "https://www.huntress.com/blog/rss.xml", "quick": True},
    "Black Hills InfoSec": {"rss": "https://www.blackhillsinfosec.com/blog/feed/", "quick": True},
    "SpecterOps Blog": {"rss": "https://posts.specterops.io/feed", "quick": True},
    "Red Canary Blog": {"rss": "https://redcanary.com/blog/feed/", "quick": True},
    "Sophos X-Ops": {"rss": "https://news.sophos.com/en-us/feed/", "quick": True},
    "WithSecure Labs": {"rss": "https://labs.withsecure.com/publications/rss", "quick": True},
    # ── Vulnerabilidades web, GitHub Security y novedades añadidas ──
    "GitHub Security Blog": {"rss": "https://github.blog/security/feed/", "quick": True},
    "MSRC (Microsoft Security)": {"rss": "https://msrc.microsoft.com/blog/feed/", "quick": True},
    "GitHub Changelog": {"rss": "https://github.blog/changelog/feed/", "quick": True},
    "Threatpost": {"rss": "https://threatpost.com/feed/", "quick": True},
    "The Register Security": {"rss": "https://www.theregister.com/security/headlines.atom", "quick": True},
    "Dark Reading": {"rss": "https://www.darkreading.com/rss.xml", "quick": True},
    "ESET WeLiveSecurity": {"rss": "https://www.welivesecurity.com/feed/", "quick": True},
    "Snyk Blog": {"rss": "https://snyk.io/blog/feed/", "quick": True},
    "Veracode Blog": {"rss": "https://www.veracode.com/blog/feed", "quick": True},
    "arXiv cs.CR (Security)": {"rss": "https://rss.arxiv.org/rss/cs.CR", "quick": True},
    "TechRepublic": {"rss": "https://www.techrepublic.com/rssfeeds/", "quick": True},
    # ── GitHub Topics (Security) ──
    "GitHub Topic Security": {"url": "https://github.com/topics/security?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Cybersecurity": {"url": "https://github.com/topics/cybersecurity?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Vulnerability": {"url": "https://github.com/topics/vulnerability?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Penetration Testing": {"url": "https://github.com/topics/penetration-testing?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic CTF": {"url": "https://github.com/topics/ctf?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Malware": {"url": "https://github.com/topics/malware?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Encryption": {"url": "https://github.com/topics/encryption?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic Firewall": {"url": "https://github.com/topics/firewall?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic SIEM": {"url": "https://github.com/topics/siem?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    "GitHub Topic OSINT": {"url": "https://github.com/topics/osint?o=desc&s=stars", "tipo": "herramienta", "subtipo": "github-topic", "selector": "article a[href]"},
    # ── Fuentes de herramientas ──
    "GitHub Trending": {"url": "https://github.com/trending", "tipo": "herramienta", "subtipo": "github", "selector": "article a[href]"},
    # ── Noticias IA: RSS feeds ──
    "The Decoder RSS": {"rss": "https://the-decoder.com/feed/", "quick": True},
    "MarkTechPost RSS": {"rss": "https://www.marktechpost.com/feed/", "quick": True},
    "VentureBeat AI RSS": {"rss": "https://venturebeat.com/category/ai/feed/", "quick": True},
    "AI News": {"rss": "https://www.artificialintelligence-news.com/feed/", "quick": True},
    "Towards AI": {"rss": "https://pub.towardsai.net/feed", "quick": True},
    "Analytics India Magazine": {"rss": "https://analyticsindiamag.com/feed/", "quick": True},
    "AI Supremacy RSS": {"rss": "https://aisupremacy.substack.com/feed", "quick": True},
    "Product Hunt RSS": {"rss": "https://www.producthunt.com/feed", "quick": True},
    "Product Hunt AI": {"url": "https://www.producthunt.com/topics/artificial-intelligence", "selector": "a[href*='/posts/']", "tipo": "herramienta", "quick": True},
    "There's An AI For That": {"url": "https://theresanaiforthat.com", "selector": "a[href*='/s/']", "tipo": "herramienta", "quick": True},
    # ── Fuentes nuevas (agregadas) ──
    # Español tech/media
    "Vitónica": {"rss": "https://www.vitonica.com/tag/vitonica/rss2.xml", "quick": True},
    "Andro4all": {"rss": "https://andro4all.com/feed/", "quick": True},
    "El Confidencial Teknautas": {"rss": "https://rss.elconfidencial.com/tecnologia/", "quick": True},
    "Microsiervos": {"rss": "https://www.microsiervos.com/index.xml", "quick": True},
    "La Mente es Maravillosa": {"rss": "https://lamenteesmaravillosa.com/feed/", "quick": True},
    # AI/DevTools
    "404 Media": {"rss": "https://www.404media.co/rss/", "quick": True},
    "DeepLearning.ai": {"rss": "https://www.deeplearning.ai/blog/rss.xml", "quick": True},
    "Two Minute Papers": {"rss": "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg", "quick": True},
    "Ahead of AI (Raschka)": {"rss": "https://magazine.sebastianraschka.com/feed", "quick": True},
    "BAIR Blog": {"rss": "https://bair.berkeley.edu/blog/feed.xml", "quick": True},
    "arXiv cs.AI": {"rss": "https://rss.arxiv.org/rss/cs.AI", "quick": True},
    # ── AI Tools / Products blogs ──
    "OpenAI Blog": {"rss": "https://openai.com/blog/rss.xml", "quick": True},
    "OpenAI News RSS": {"rss": "https://openai.com/news/rss.xml", "quick": True},
    "Anthropic Blog": {"url": "https://www.anthropic.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Anthropic Research": {"url": "https://www.anthropic.com/research", "selector": "a[href*='/research/']", "tipo": "noticia", "quick": True},
    "Groq Blog": {"url": "https://groq.com/blog/", "selector": "article a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "ElevenLabs Blog": {"url": "https://elevenlabs.io/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Runway ML Blog": {"url": "https://runwayml.com/blog/", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Perplexity Blog": {"url": "https://www.perplexity.ai/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Hugging Face Blog": {"rss": "https://huggingface.co/blog/feed.xml", "quick": True},
    "Replicate Blog": {"url": "https://replicate.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Together AI Blog": {"url": "https://www.together.ai/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Fireworks AI Blog": {"url": "https://fireworks.ai/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "DeepInfra Blog": {"url": "https://deepinfra.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Suno Blog": {"url": "https://suno.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Pika Blog": {"url": "https://pika.art/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Luma AI Blog": {"url": "https://lumalabs.ai/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "HeyGen Blog": {"url": "https://www.heygen.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Descript Blog": {"url": "https://www.descript.com/blog", "selector": "a[href*='/blog/']", "tipo": "noticia", "quick": True},
    "Leonardo AI Docs": {"url": "https://docs.leonardo.ai", "selector": "a[href*='/docs/']", "tipo": "noticia", "quick": True},
    "Midjourney Docs": {"url": "https://docs.midjourney.com", "selector": "a[href*='/docs/']", "tipo": "noticia", "quick": True},
    "Gamma Help": {"url": "https://help.gamma.app", "selector": "a[href*='/hc/']", "tipo": "noticia", "quick": True},
    # Comunidades
    "GitHub Blog": {"rss": "https://github.blog/news-insights/feed/", "quick": True},
    "Slashdot": {"rss": "http://rss.slashdot.org/Slashdot/slashdotMain", "quick": True},
}
