name: download_workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  download_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: donwload changes repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: donwload and update link
        run: bash ./downloadFile.sh
        shell: bash
      - name: Update Github repo
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./index.html  
          git commit -m "download and update"
          git push
      - name: Deploy to jorbencasdownloaderdocument.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'jorbencasdownloaderdocument.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
          branch: master
          force: true
          message: 'Deployed by Github Actions'