name: main_workflow
on: 
  push:
    branches:
      -  nodejs_linter_jo
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  download_and_update:
    runs-on: ubuntu-latest
    steps:
      -name: donwload changes repo
       run: |
          git config user.name jorbencas
          git config user.email jorbencas@gmail.com
          git fetch

      - name: donwload and update link
        run: bash ./downloadFile.sh
        shell: bash

      - name: Update Github repo
        run: |
          git config user.name jorbencas
          git config user.email jorbencas@gmail.com
          git checkout master
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update link to download file"
          git push origin master 

  deployment_job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'jorbencasdownloaderdocument.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}