name: main_workflow
on: 
  push:
    branches:
      -  nodejs_linter_jo
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
   wget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3