name: download_workflow
on:
  push
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
jobs:
  download_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: donwload changes repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: donwload and update link
        run: bash ./downloadFile.sh
        shell: bash
      - name: Update Github repo
        run: |
          git config user.name jorbencas
          git config user.email jorbencas@gmail.com
          git add .  
          git commit -m "[bot] update link to download file"
          git push
      - name: Deploy to jorbencasdownloaderdocument.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'jorbencasdownloaderdocument.surge.sh'
          project: '.'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}