name: main_workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
   wget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: donwload and update link
        shell: bash
        run: bash ./downloadFile.sh
