name: 🍿🎥✮⋆˙Monitor Netflix Rating

# Control de ejecución
on:
  schedule:
    - cron: '0 0 */3 * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permisos necesarios para que el bot pueda subir el archivo de texto al repo
    permissions:
      contents: write

    steps:
      # 1. Descarga el código de tu repositorio
      - name: Checkout de código
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Descargar Cache anterior
        uses: actions/download-artifact@v4
        with:
          name: netflix-cache
        continue-on-error: true # La primera vez no existirá
      # 4. Ejecuta tu script de Python
      - name: Ejecutar monitor de Netflix
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TOKEN_API_ID: ${{ secrets.TOKEN_API_ID }}
        run: python check_netflix.py
      - name: Subir Cache actualizada
        uses: actions/upload-artifact@v4
        with:
          name: netflix-cache
          path: netflix_cache.json
      # 5. Guarda los cambios en el archivo de texto (para no repetir mensajes)
      - name: Guardar estado y hacer Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add netflix_cache.json || echo "No hay cambios en el archivo de estado"
          git commit -m "Actualización automática de estado de clasificación" || echo "Nada que commitear"
          git push || echo "No hay cambios para subir"
